# Generated by Django 5.0.2 on 2024-03-04 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('days', models.IntegerField(verbose_name='Davomiyligi ')),
                ('_from', models.DateField(max_length=100, verbose_name='Boshlanish sanasi ')),
                ('_to', models.DateField(max_length=100, verbose_name='Tudash sanasi ')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Lavhalar')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('included_services', models.TextField(verbose_name='Mavjud xizmatlar ')),
                ('contact', models.IntegerField(verbose_name='Number')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram manzili ')),
                ('Instagram', models.URLField(blank=True, verbose_name='Instagram manzili ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
