# Generated by Django 5.0.1 on 2024-03-04 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=100, verbose_name='Firma nomi')),
            ],
        ),
        migrations.AlterField(
            model_name='facilitymodel',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firma.agencymodel'),
        ),
    ]
